[package]
name = "pcap-rewrite"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
edition = "2018"

[dependencies]
# env_logger = "0.6"
libpcap-tools = { version="0.1.0", path="../libpcap-tools" }
log = "0.4"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
std-logger = "0.3"
xz2 = "0.1"

[dependencies.clap]
version = "2"
default-features = false

[dependencies.pcap-parser]
version = "0.8"
features = ["data", "serialize"]
