[package]
name = "pcap-rewrite"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
edition = "2018"

description = "Pcap file conversion/rewrite tool"
categories = ["network-programming"]

keywords    = ["pcap", "network", "tools"]
readme      = "../README.md"
license     = "MIT/Apache-2.0"

repository    = "https://github.com/rusticata/pcap-analyzer.git"
homepage      = "https://github.com/rusticata/pcap-analyzer"

[badges]
travis-ci                         = { repository = "rusticata/pcap-analyzer" }
is-it-maintained-open-issues      = { repository = "rusticata/pcap-analyzer" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
libpcap-tools = { version="0.1.0", path="../libpcap-tools" }
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
pnet_packet = "0.28"
simplelog = { version="0.11", default-features = false }
xz2 = "0.1"

[dependencies.clap]
version = "2"
default-features = false

[dependencies.pcap-parser]
version = "0.13"
features = ["data", "serialize"]
