stages:
  - build
  - test
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

before_script:
  - apt-get update -yq
# - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y {{ DEPENDENCIES }}

test:
  stage: test
  image: 'rust:latest'
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

test-nightly:
  stage: test
  image: 'rust:latest'
  before_script:
    - rustup default nightly
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

clippy: 
  stage: test
  image: 'rust:latest'
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -- -D clippy::all
  allow_failure: true

fmt: 
  stage: test
  image: 'rust:latest'
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check
  allow_failure: true

pages:
  stage: deploy
  image: 'rust:latest'
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=/pcap-analyzer/libpcap_analyzer/">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master

cache:
  paths:
    - cargo/
