language: rust
sudo: false
matrix:
  include:
    - rust: stable
      env:
       - NAME="stable"
    - rust: nightly
      env:
       - NAME="nightly"
       - BENCH=0
script:
  - |
      cargo build --all-targets --verbose &&
      cargo test --verbose &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose)
