[package]
name = "pcap-analyzer"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
libpcap-analyzer = { path="../libpcap-analyzer" }
log = "0.4"

[dependencies.clap]
version = "2"
default-features = false
