[package]
name = "libpcap-analyzer"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
lazy_static = "1.2"
libpcap-tools = { path="../libpcap-tools" }
log = "0.4"
nom = "4.2"
pnet_base = "0.22.0"
pnet_macros_support = "0.22.0"
pnet_packet = "0.22.0"
rand="0.6"
toml="0.5"

[dependencies.rusticata]
# path = "../../rusticata"
git = "https://github.com/rusticata/rusticata.git"

[dependencies.pcap-parser]
version = "0.5"
features = ["data"]
