[package]
name = "pcap-info"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
edition = "2018"

description = "Pcap file information tool"
categories = ["network-programming"]

keywords    = ["pcap", "network", "tools"]
readme      = "../README.md"
license     = "MIT/Apache-2.0"

repository    = "https://github.com/rusticata/pcap-analyzer.git"
homepage      = "https://github.com/rusticata/pcap-analyzer"

[badges]
travis-ci                         = { repository = "rusticata/pcap-analyzer" }
is-it-maintained-open-issues      = { repository = "rusticata/pcap-analyzer" }
maintenance                       = { status     = "actively-developed" }

[dependencies]
chrono = "0.4"
digest = "0.9"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
ripemd160 = "0.9"
sha-1 = "0.9"
sha2 = "0.9"
xz2 = "0.1"

[dependencies.clap]
version = "2"
default-features = false

[dependencies.pcap-parser]
version = "0.10"
features = ["data", "serialize"]
