[package]
name = "libpcap-tools"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
edition = "2018"

[dependencies]
circular = "0.2"
lazy_static = "1.2"
log = "0.4"
nom = "4.2"

[dependencies.pcap-parser]
version = "0.5"
features = ["data"]
